title: Neural Network from Scratch Documentation
description: A simple neural network implementation made with just Python and NumPy.
show_downloads: true
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown Github Pages Guide: https://nicolas-van.github.io/easy-markdown-to-github-pages/
# Cayman documentation: https://github.com/pages-themes/cayman