plugins:
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-relative-links

# Markdown Github Pages Guide: https://nicolas-van.github.io/easy-markdown-to-github-pages/
# Cayman documentation: https://github.com/pages-themes/cayman